# Generated by Django 6.1.1 on 2026-10-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_No', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Bike_Model', models.CharField(max_length=20)),
                ('Service_Date', models.DateField()),
                ('Service_Cost', models.FloatField()),
                ('Address', models.TextField()),
                ('Service_Type', models.CharField(max_length=30)),
            ],
        ),
    ]
